# Generated by Django 3.2 on 2021-04-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_auto_20210409_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
